#!/bin/sh

name=rust
version=1.0.0
revision=1
git_url=https://gitlab.com/mishakov/rust-pmos.git
commit="73e342bd51eb0d9762febd5cc105a0869d8d066d"

early_prepare() {
    git submodule update --init --recursive --depth=1
}