#!/bin/sh

name=rust
version=1.0.0
revision=1
git_url=https://gitlab.com/mishakov/rust-pmos.git
commit="e3594e6e4f6245fb4a95284665ed4b2051eda746"

early_prepare() {
    git submodule update --init --recursive --depth=1
}