#!/bin/sh

version=0.0.1
revision=1

source_dir=userspace/devicesd
deps="mlibc mlibc-headers pmos-containers pmos-helpers"
hostdeps="$TOOLCHAIN_DEPS $CXX_DEPS"

configure() {
    cmake_configure
}

build() {
    make -j ${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
    cp ${source_dir}/devicesd.yaml "${dest_dir}/boot/devicesd.yaml"
}