#!/bin/sh

name=ahcid
version=0.0.1
revision=1

source_dir=userspace/ahcid
deps="libc libc-headers libcxx"
hostdeps="clang"

configure() {
    cmake -S ${source_dir} -DTARGET_ARCH=${JINX_ARCH} -DCMAKE_SYSROOT=${sysroot_dir}
}

build() {
    make -j ${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
    cp ${source_dir}/ahcid.yaml "${dest_dir}/boot/ahcid.yaml"
}