#!/bin/sh

name=bootstrapd
version=0.0.1
revision=1

source_dir=userspace/bootstrapd
deps="libc libc-headers"
hostdeps="clang"
allow_network=yes

# TODO: Move libyaml to a separate recipe

configure() {
    cmake -S ${source_dir} -DTARGET_ARCH=${JINX_ARCH} -DCMAKE_SYSROOT=${sysroot_dir} -DCMAKE_POLICY_VERSION_MINIMUM=3.5
}

build() {
    make -j ${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
}