#!/bin/sh

name=hyper-disk-image
version=1
revision=1

source_dir=scripts
imagedeps="e2fsprogs mtools fdisk"
deps="hyper-config kernel bootstrapd ${BOOT_SERVICES}"
hostdeps="hyper"

build() {
    SYSROOT="$sysroot_dir" \
    ${source_dir}/make_hyper_disk_image.sh "$build_dir/pmos-hyper.img" "${BOOT_SERVICES}" "hyper.cfg"
}