#!/bin/sh

name=hyper-iso
version=1
revision=1

source_dir=scripts
imagedeps="xorriso e2fsprogs mtools"
deps="hyper-config kernel bootstrapd ${BOOT_SERVICES}"
hostdeps="hyper"

build() {
    SYSROOT="$sysroot_dir" \
    ${source_dir}/make_hyper_iso.sh "$build_dir/pmos-hyper.iso" "${BOOT_SERVICES}" "hyper.cfg"
}