#!/bin/sh

name=kernel
version=0.0.1
revision=1

source_dir=kernel
deps="libcxx libc-headers"
hostdeps="clang"

configure() {
    cmake -S ${source_dir} -DTARGET_ARCH=${JINX_ARCH} -DSYSROOT=${sysroot_dir}
}

build() {
    make -j ${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
}