#!/bin/sh

name=libc++
revision=1
from_source=clang-src
deps="libc-headers libc"
hostdeps="clang"

triplet="${JINX_ARCH}-pmos"

configure() {
    cmake -S ${source_dir}/runtimes \
        -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind;compiler-rt" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr/ \
        -DLLVM_TARGET_TRIPLE=loongarch64-pmos \
        -DCMAKE_CXX_COMPILER_TARGET="${triplet}" \
        -DCMAKE_C_COMPILER="clang" \
        -DCMAKE_CXX_COMPILER="clang++" \
        -DCMAKE_C_COMPILER_TARGET="${triplet}" \
        -DCMAKE_ASM_COMPILER_TARGET="${triplet}" \
        -DCOMPILER_RT_BUILD_BUILTINS=ON \
        -DCMAKE_C_FLAGS="--sysroot=${sysroot_dir} -nostartfiles" \
        -DCMAKE_CXX_FLAGS="--sysroot=${sysroot_dir} -nostdlib" \
        -DLIBCXXABI_USE_LLVM_UNWINDER=true \
        -DLIBCXX_ENABLE_SHARED=OFF \
        -DLIBUNWIND_ENABLE_SHARED=OFF \
        -DLIBCXXABI_ENABLE_SHARED=OFF \
        -DCOMPILER_RT_BUILD_BUILTINS=ON \
        -DCOMPILER_RT_BUILD_ORC=OFF \
        -DCOMPILER_RT_BUILD_SANITIZERS=OFF \
        -DCOMPILER_RT_BUILD_MEMPROF=OFF \
        -DCOMPILER_RT_BUILD_XRAY=OFF \
        -DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
        -DCOMPILER_RT_BUILD_PROFILE=OFF \
        -DCOMPILER_RT_INSTALL_LIBRARY_DIR="/usr/lib" \
        -DCOMPILER_RT_BUILD_CTX_PROFILE=OFF
}

build() {
    make -j ${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
}