#!/bin/sh

name=libcxx
from_source=clang-src
revision=1
deps="mlibc-headers mlibc"
hostdeps="clang compiler-rt"
imagedeps="python3 build-essential"

triplet="${JINX_ARCH}-pmos"

if [ ${JINX_ARCH} = "i686" ]; then
    EXTRA_FLAGS="-DCAN_TARGET_i386=1"
fi

configure() {
    cmake -S ${source_dir}/runtimes \
        -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr/ \
        -DLLVM_TARGET_TRIPLE=${triplet} \
        -DCMAKE_CXX_COMPILER_TARGET="${triplet}" \
        -DCMAKE_C_COMPILER="clang" \
        -DCMAKE_CXX_COMPILER="clang++" \
        -DCMAKE_C_COMPILER_TARGET="${triplet}" \
        -DCMAKE_ASM_COMPILER_TARGET="${triplet}" \
        -DCOMPILER_RT_BUILD_BUILTINS=ON \
        -DCMAKE_C_FLAGS="--sysroot=${sysroot_dir} -nostartfiles -lclang_rt.builtins" \
        -DCMAKE_CXX_FLAGS="--sysroot=${sysroot_dir} -nostdlib -lclang_rt.builtins" \
        -DLIBCXXABI_USE_LLVM_UNWINDER=true \
        -DCMAKE_C_COMPILER_WORKS=ON \
        -DCMAKE_CXX_COMPILER_WORKS=ON \
        ${EXTRA_FLAGS}
}

build() {
    make -j ${parallelism} VERBOSE=1
}

package() {
    DESTDIR="${dest_dir}" make install
}