#!/bin/sh

name=limine-disk-image
version=1
revision=1

source_dir=scripts
imagedeps="e2fsprogs mtools fdisk"
deps="limine-config kernel bootstrapd ${BOOT_SERVICES}"
hostdeps="limine"

build() {
    SYSROOT="$sysroot_dir" \
    ${source_dir}/make_limine_disk_image.sh "$build_dir/pmos.img" "${BOOT_SERVICES}" "limine.conf"
}