#!/bin/sh

name=limine-config
version=1
revision=1

source_dir=scripts

build() {
    CONFIG_FILE="limine.conf"
    ${source_dir}/make_limine_cnf.sh "$CONFIG_FILE" "$BOOT_SERVICES"
}

package() {
    mkdir -p "${dest_dir}/boot"
    cp "limine.conf" "${dest_dir}/boot/limine.conf"
}