#!/bin/sh

name=pmbus
version=1.0.0
revision=1

source_dir=userspace/pmbus
deps="libc pmos-rust-lib libcxx rust-core"
hostdeps="cargo rust clang"
source_hostdeps="cargo"
allow_network=yes

# prepare() {
#     CARGO_HOME="${build_dir}/.cargo" \
#     cargo fetch --target ${JINX_ARCH}-unknown-pmos
# }

build() {
    TARGET_CC="clang" \
    cargo_build_nolock
}

# package() {
#     CARGO_HOME="${build_dir}/.cargo" \
#     DESTDIR="${dest_dir}" \
#     RUSTFLAGS="-C link-arg=--sysroot=${SYSROOT} -C linker=clang++ -C link-arg=--target=${JINX_ARCH}-unknown-pmos -C link-arg=-lunwind -C link-arg=-static" \
#     cargo install --target ${JINX_ARCH}-unknown-pmos --root ${dest_dir} --path ${source_dir}
# }
