#!/bin/sh

name=pmbus
version=1.0.0
revision=1

source_dir=userspace/pmbus
deps="libc pmos-rust-lib libcxx"
hostdeps="cargo rust clang"
source_hostdeps="cargo"
allow_network=yes

# prepare() {
#     CARGO_HOME="${build_dir}/.cargo" \
#     cargo fetch --target ${JINX_ARCH}-unknown-pmos
# }

build() {
    TARGET_CC="clang" \
    cargo_build_nolock
}

package() {
    mkdir -p ${dest_dir}/boot
    cp -r ${build_dir}/builds/pmbus/${RUST_TARGET}/release/pmbus ${dest_dir}/boot/
    cp ${source_dir}/pmbus.yaml "${dest_dir}/boot/pmbus.yaml"
}
