#ifndef KERNEL_ERRORS_H
#define KERNEL_ERRORS_H

#define SUCCESS                   0ULL
#define ERROR_NOT_SUPPORTED      -1ULL
#define ERROR_NOT_IMPLEMENTED    -2ULL
#define ERROR_NO_PERMISSION      -3ULL
#define ERROR_OUT_OF_RANGE       -4ULL
#define ERROR_UNALLIGNED         -5ULL
#define ERROR_PAGE_PRESENT       -6ULL
#define ERROR_GENERAL            -7ULL
#define ERROR_OUT_OF_MEMORY      -8ULL
#define ERROR_HUGE_PAGE          -9ULL
#define ERROR_PAGE_NOT_ALLOCATED -10ULL
#define ERROR_PAGE_NOT_PRESENT   -11ULL
#define ERROR_WRONG_PAGE_TYPE    -12ULL
#define ERROR_ALREADY_BLOCKED    -13ULL
#define ERROR_NO_SUCH_PROCESS    -14ULL
#define ERROR_PROCESS_INITED     -15ULL
#define ERROR_CANT_MESSAGE_SELF  -16ULL
#define ERROR_NO_MESSAGES        -17ULL
#define ERROR_PORT_DOESNT_EXIST  -18ULL
#define ERROR_PORT_CLOSED        -19ULL
#define ERROR_PAGE_NOT_SHARED    -20ULL
#define ERROR_NOT_PAGE_OWNER     -21ULL
#define ERROR_ALREADY_PAGE_OWNER -22ULL
#define ERROR_SPECIAL_PAGE       -23ULL
#define ERROR_NODESTINATION      -24ULL

#endif