#!/bin/sh

version=0.0.1
revision=1

source_dir=userspace/terminald
deps="mlibc mlibc-headers pmoscxx $CXX_DEPS"
hostdeps="$TOOLCHAIN_DEPS"

configure() {
    cmake_configure
}

build() {
    make -j ${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
    cp ${source_dir}/terminald.yaml "${dest_dir}/boot/terminald.yaml"
}