#!/bin/sh

version=0.0.1
revision=1

source_dir=userspace/processd
deps="mlibc mlibc-headers pmoscxx frigg $CXX_DEPS"
hostdeps="$TOOLCHAIN_DEPS"

configure() {
    cmake_configure
}

build() {
    make -j ${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
    cp ${source_dir}/processd.yaml "${dest_dir}/boot/processd.yaml"
}