#include <signal.h>

const char * const sys_siglist[NSIG] = {
    "Unknown signal",
    "Floating point exception",
    "Illegal instruction",
    "Interrupt",
    "Segmentation fault",
    "Terminated",
    "Alarm clock",
    "Bus error",
    "Child process exited",
    "Continued",
    "Hangup",
    "Killed",
    "Pipe write error",
    "Quit",
    "Stopped",
    "Stopped (tty input)",
    "Stopped (tty output)",
    "User defined signal 1",
    "User defined signal 2",
    "Pollable event",
    "Profiling timer expired",
    "Bad system call",
    "Trace/breakpoint trap",
    "Urgent data",
    "Virtual timer expired",
    "CPU time limit exceeded",
    "File size limit exceeded",
    "Aborted",
    "Window size change",
    "Power failure",
    "Status request",
    "Real time signal 0",
    "Real time signal 1",
    "Real time signal 2",
    "Real time signal 3",
    "Real time signal 4",
    "Real time signal 5",
    "Real time signal 6",
    "Real time signal 7",
    "Real time signal 8",
    "Real time signal 9",
    "Real time signal 10",
    "Real time signal 11",
    "Real time signal 12",
    "Real time signal 13",
    "Real time signal 14",
    "Real time signal 15",
    "Real time signal 16",
    "Real time signal 17",
    "Real time signal 18",
    "Real time signal 19",
    "Real time signal 20",
    "Real time signal 21",
    "Real time signal 22",
    "Real time signal 23",
    "Real time signal 24",
    "Real time signal 25",
    "Real time signal 26",
    "Real time signal 27",
    "Real time signal 28",
    "Real time signal 29",
    "Real time signal 30",
    "Real time signal 31",
};