#!/bin/sh

name=ps2d
version=0.0.1
revision=1

source_dir=userspace/ps2d
deps="mlibc mlibc-headers pmos-helpers"
hostdeps="$TOOLCHAIN_DEPS"

configure() {
    cmake_configure
}

build() {
    make -j ${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
    cp ${source_dir}/ps2d.yaml "${dest_dir}/boot/ps2d.yaml"
}