#!/bin/sh

version=1
revision=2

source_dir=scripts

build() {
    CONFIG_FILE="grub.cfg"
    LIBRARIES=$LIBRARIES \
    ${source_dir}/make_grub_config.sh "$CONFIG_FILE" "$BOOT_SERVICES"
}

package() {
    mkdir -p "${dest_dir}/boot"
    cp "grub.cfg" "${dest_dir}/boot/grub.cfg"
}