#ifndef _FILESYSTEM_ERRORS_H
#define _FILESYSTEM_ERRORS_H
#include <errno.h>


#define FS_SUCCESS 0
#define FS_ERROR_FILE_NOT_FOUND ENOENT
#define FS_ERROR_FILE_IS_DIRECTORY EISDIR
#define FS_ERROR_OUT_OF_MEMORY ENOMEM
#define FS_ERROR_NOT_CONSUMER EPERM


#endif // _FILESYSTEM_ERRORS_H