function(LOAD_PLATFORM ARCH)
    file(GLOB_RECURSE PLATFORM_SRCS
        ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/${ARCH}/*.c
        ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/${ARCH}/*.cc
        ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/${ARCH}/*.S)

    include(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/${ARCH}/flags.cmake)

    set(PLATFORM_SRCS ${PLATFORM_SRCS} PARENT_SCOPE)

    set(PLATFORM_C_FLAGS ${PLATFORM_C_FLAGS} PARENT_SCOPE)
    set(PLATFORM_CXX_FLAGS ${PLATFORM_CXX_FLAGS} PARENT_SCOPE)
    set(PLATFORM_ASM_FLAGS ${PLATFORM_ASM_FLAGS} PARENT_SCOPE)

    set(ENABLE_DTB 1 PARENT_SCOPE)
endfunction()