#!/bin/sh

revision=1
from_source=gcc
imagedeps="gcc build-essential pkg-config libgmp-dev libmpfr-dev libmpc-dev flex texinfo bison libisl-dev gettext"
deps="mlibc-headers mlibc"
hostdeps="$TOOLCHAIN_DEPS"

configure() {
    multilib=
    if [ "${JINX_ARCH}" = "m68k" ]; then
        multilib=--disable-multilib
    fi
    ${source_dir}/configure --target=${JINX_ARCH}-pmos --with-sysroot="${sysroot}" --prefix=${prefix} --enable-languages=c,c++ --enable-shared --with-pic ${multilib}
}

build() {
    make -j ${parallelism} all-target-libstdc++-v3 all-target-libatomic
}

package() {
    make DESTDIR="${dest_dir}" install-target-libstdc++-v3 install-target-libatomic
}