#!/bin/sh

revision=3
from_source=gcc
imagedeps="gcc build-essential pkg-config libgmp-dev libmpfr-dev libmpc-dev flex texinfo bison libisl-dev gettext"
deps="mlibc-headers mlibc"
hostdeps="$TOOLCHAIN_DEPS"

configure() {
    ${source_dir}/configure --target=${JINX_ARCH}-pmos --with-sysroot="${sysroot}" --prefix=${prefix} --enable-languages=c,c++ --enable-shared --with-pic
}

build() {
    make -j ${parallelism} all-target-libstdc++-v3
}

package() {
    make DESTDIR="${dest_dir}" install-target-libstdc++-v3
}