#!/bin/sh

version=0.0.1
revision=1

source_dir=kernel
builddeps="mlibc-headers mlibc pmos-containers $CXX_DEPS"
hostdeps="$TOOLCHAIN_DEPS"

configure() {
    cmake_configure
}

build() {
    make -j ${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
}