#! /bin/sh

name=cargo
from_source=cargo-src
revision=1
imagedeps="build-essential libssl-dev pkg-config cargo gcc"
hostrundeps="rust"
allow_network=yes

configure() {
    cp -rp "${source_dir}"/. ./

        CARGO_HOME="${build_dir}/.cargo" \
    cargo fetch \
        --target ${RUST_HOST_TARGET}
}

build() {
        CARGO_HOME="${build_dir}/.cargo" \
    cargo build \
        --release \
        --target x86_64-unknown-linux-gnu \
        -j${parallelism}
}

package() {
    find target/${RUST_HOST_TARGET}/release \
        -maxdepth 1 \
        -type f \
        -executable \
        -exec install -D -m755 -t "${dest_dir}${prefix}/bin" {} +

    # Strip binaries
    strip_command=strip \
    post_package_strip
}