#!/bin/sh

name=rust
revision=1
from_source=rust
allow_network=yes

configure() {
    cat <<EOF > config.toml
change-id = 148671

[llvm]
download-ci-llvm = false
targets = "X86"

[build]
target = ["x86_64-unknown-pmos", "x86_64-unknown-linux-gnu"]
build-dir = "${base_dir}/host-builds/rust"
docs = false

[install]
prefix = "${prefix}"
sysconfdir = "${prefix}/etc"
EOF

    cat <<EOF > bootstrap.toml
[llvm]
change-id = 148671
download-ci-llvm = false
EOF
}

build() {
    CARGO_HOME="${build_dir}/.cargo" ${source_dir}/x.py build --stage 2 -j${parallelism}
}

package() {
    CARGO_HOME="${build_dir}/.cargo" DESTDIR="${dest_dir}" ${source_dir}/x.py install -j${parallelism}

    
    find ${dest_dir} -name "*.old" -delete

    # strip_command=strip
    # post_package_strip
}