#!/bin/sh

revision=2
from_source=gcc
imagedeps="gcc build-essential pkg-config libgmp-dev libmpfr-dev libmpc-dev flex texinfo bison libisl-dev gettext"
deps="mlibc-headers"
hostdeps="binutils"

configure() {
    ${source_dir}/configure --target=${JINX_ARCH}-pmos --with-sysroot="${sysroot}" --enable-languages=c,c++
}

build() {
    make -j ${parallelism} all-gcc all-target-libgcc
}

package() {
    make DESTDIR="${dest_dir}" install-gcc install-target-libgcc
}