#!/bin/sh

version=0.0.1
revision=1

source_dir=userspace/ns16550
deps="mlibc mlibc-headers pmoscxx"
hostdeps="$TOOLCHAIN_DEPS $CXX_DEPS"

configure() {
    cmake_configure
}

build() {
    make -j ${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
    cp ${source_dir}/ns16550.yaml "${dest_dir}/boot/ns16550.yaml"
}